apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    k8s-app: dotnetapp
  name: dotnetapp
  namespace: default
  resourceVersion: "230074"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/dotnetapp
  uid: ceea40b4-722b-467d-b5f5-b971bc1bddca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dotnetapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: dotnetapp
      name: dotnetapp
    spec:
      containers:
      - image: direct2sanjeev/devsecops:devsecops
        imagePullPolicy: IfNotPresent
        name: dotnetapp
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-22T16:12:15Z"
    lastUpdateTime: "2020-03-22T16:12:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-22T16:12:13Z"
    lastUpdateTime: "2020-03-22T16:12:15Z"
    message: ReplicaSet "dotnetapp-585c748894" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
