apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dotnetapp
  name: dotnetapp
  namespace: default
  resourceVersion: "230081"
  selfLink: /api/v1/namespaces/default/services/dotnetapp
  uid: 7a27c873-84f2-4438-9111-d76b700a3115
spec:
  clusterIP: 10.0.121.174
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-8080-80-l2nvx
    nodePort: 31270
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: dotnetapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.44.40.236
